version with react
DashaGoryacheva/task-with-webpack pull request #1
Opened 2022-12-29 22:03 UTC by DashaGoryacheva

2022-12-31 03:33 UTC, katekrivets commented
Я не совсем понимаю куда в новой ветке пропал .gitignore ? папка node_modules не должна попадать гит

2022-12-31 03:46 UTC, katekrivets requested changes

2022-12-31 03:46 UTC, katekrivets commented on src/Secondbl.js
> +class Secondbl extends Component {
https://github.com/airbnb/javascript/tree/master/react#naming

неплохой пример того как стоит именовать компоненты

Это касается всех компонент с окончанием bl :)

2022-12-31 03:46 UTC, katekrivets commented on index.html
> +<!--<div class="container">
удали неиспользуемый код

2023-01-07 00:09 UTC, katekrivets commented
Следующим шагом предлагаю реализовать приложение (Iteration 1):
- давай представим, что у нас есть список музыкальных треков и альбомов
- у нас есть файл songs.json, в нем выкачанный список песен Валерия Меладзе из spotify :) 
https://developer.spotify.com/documentation/web-api/reference/#/operations/search - здесь можно почитать про формат, в котором приходят данные - если непонятно как читать, велкам 
В кратце, там объект в нем список треков:
`{ "tracks": { "items": [ // ... здесь будут треки ] }  }`
В каждом треке есть название трека, список исполнителей, информация об альбоме, дата выпуска альбома и фото исполнителя.

Задача: 
1) добавить файл в проект
2) вычитать содержимое
3) создать приложение в котором есть 4 страницы 
  - список треков -> путь "/"
  - страница исполнителя "/artist/{id}"
  - страница информации об альбоме "/album/{id}"
  - страница трека "/track/{id}"
Чтобы это сделать:
Шаг 1 - подключи и разберись с react-router и создай простые компоненты, каждая из которых будет рендериться по заданному пути (описание выше), на каждой странице просто должно рендериться ее название tracks, artist, album, track - ничего более.
Шаг 2 - отрисовка списка треков с использованием react, разделением на компоненты и использованием sass - последнее надо подключить в проект https://sass-lang.com/, для отрисовки используем данные из songs.json
Шаг 3 - дальше страница исполнителя, альбома и трек для отрисовки используем данные из songs.json

Каждый шаг - отдельный пул реквест. 
Любые вопросы - велкам :)

2023-01-09 20:18 UTC, DashaGoryacheva commented on src/Secondbl.js
> +class Secondbl extends Component {
исправила

2023-01-09 21:28 UTC, DashaGoryacheva commented on index.html
> +<!--<div class="container">
+

2023-01-10 19:48 UTC, merged