React router tracklist
DashaGoryacheva/task-with-webpack pull request #3
Opened 2023-01-20 19:54 UTC by DashaGoryacheva

2023-01-20 20:36 UTC, katekrivets commented
В целом задача выполнена, посмотри комментарии 
Над css надо плотно работать.
Обрати внимание на вертикальные margins в элементах, это можно решить с помощью псевдоклассов в css.
https://developer.mozilla.org/ru/docs/Web/CSS/Pseudo-classes

2023-01-20 20:37 UTC, katekrivets commented
Когда я делаю масштаб меньше у меня уезжает фон, это значит, что если будет 3 трека, то будет то же самое
<img width="1536" alt="image" src="https://user-images.githubusercontent.com/24584506/213800924-be3391f2-bc15-4d1c-b127-eed6a59762d0.png">

2023-01-20 20:38 UTC, katekrivets commented
Еще насчет ui - обрати внимание на скриншот в задаче :) давай попробуем добиться чего-то подобного, современного и красивого, ты же не захотела бы сама таким пользоваться, правда?

2023-01-25 20:39 UTC, katekrivets requested changes

2023-01-25 20:39 UTC, katekrivets commented on src/components/Album/Album.jsx
> +            <p>ALBUM ID:{albumId}</p>
я не совсем понимаю твою любовь к <p> тегам :)
ты из семантики такое решение принимаешь или просто нравится?

2023-01-25 20:39 UTC, katekrivets commented on src/components/App.jsx
> +            <Route path='/' element={<SearchBlock/>} >
тут отступы пострадали, из-за этого сложно прочитать

2023-01-25 20:39 UTC, katekrivets commented on src/components/App.jsx
> +            <Route path='/' element={<SearchBlock/>} >
и еще не совсем понятно почему search block в <Route path='/'>
он разве не будет тогда на всех страницах отрисовываться?

2023-01-25 20:39 UTC, katekrivets commented on src/components/App.jsx
> +            <Route path='/' element={<SearchBlock/>} >
покажи скрин

2023-01-25 20:39 UTC, katekrivets commented on src/components/SearchBlock/SearchBlock.jsx
> +          <button className='search-icon'></button>
я вижу ты с иконками поразвлекалась :) 
в целом начинение хорошее, но я предлагаю тебе выбрать какую-нибудь библиотеку, например react-icons и в ней выбрать подраздел, чтобы все иконки в одном стиле были

2023-01-25 20:39 UTC, katekrivets commented on src/components/SearchBlock/SearchBlock.jsx
> +          <button className='search-icon'></button>
можешь взять любую другую, но обращай внимание на license 
в идеале надо MIT / Apache 2.0

2023-01-25 20:39 UTC, katekrivets commented on src/components/SearchBlock/searchBlock.css
> +    width: 97%;
у меня тут математика перестала сходиться с процентами, я посмотрю на реализации как выглядит

2023-01-25 20:39 UTC, katekrivets commented on src/components/SearchBlock/searchBlock.css
> +    cursor: grab;
обычно используют pointer, grab это все-таки для перетаскивания

2023-01-25 20:39 UTC, katekrivets commented on src/components/TrackList.jsx
> +          <ul type='none' className='trackList-item'>
кто-то поленился использовать BEM :)
если я правильно помню у тебя должно получиться что-то типа 
track-list_item

в classNames  обычно не используют camelCase

2023-01-25 20:39 UTC, katekrivets commented on src/components/trackList.css
> +    font-family: Arial, "Helvetica Neue";
со шрифтами отдельная история, обычно их пишут в порядке приоритета и дальше идут по убыванию и заканчивают просто типом шрифта
https://www.w3schools.com/css/css_font.asp

2023-01-25 20:39 UTC, katekrivets commented on src/components/trackList.css
> +    padding: 2%;
а каким этот padding станет если прям очень маленький экран? а если очень большой? понажимай ctrl +/ ctrl - поменяй масштаб)
мне кажется проценты в padding не совсем уместны, лучше media queries для этих целей

2023-01-25 20:39 UTC, katekrivets commented on src/components/trackList.css
> +    font-family: Arial, "Helvetica Neue";
еще можно просто в основном файле приложения один раз задать шрифт и не мучаться 
типа 
`* { font-family:  .... }`

2023-01-25 20:39 UTC, katekrivets commented on src/components/trackList.css
> +    border: 1px groove rgb(114, 113, 113);
а почему бордеры, а не модные box-shadows ? :)

2023-01-25 20:39 UTC, katekrivets commented on webpack.common.js
> + const json = require('./src/components/songs');
а это тут точно надо?

2023-01-25 20:39 UTC, katekrivets commented on src/components/App.jsx
> +            <Route path='/' element={<SearchBlock/>} >
я потыкала, пусть будет)

2023-01-25 20:41 UTC, katekrivets commented on src/components/trackList.css
> +    padding: 2%;
но тут конечно надо смотреть, я сама начала сомневаться)

2023-01-26 05:12 UTC, katekrivets commented
<img width="1383" alt="image" src="https://user-images.githubusercontent.com/24584506/214763087-b6a89da0-9025-41ce-bf8b-56164cf39570.png">

2023-01-26 05:12 UTC, katekrivets commented on src/components/utils/time.js
> +
- поправь форматирование, я вообще это не могу читать, разберись пожалуйста с prettier  ( config и расширение для vscode)

2023-01-26 05:12 UTC, katekrivets commented on src/components/utils/time.js
> +
- почитай про чистые функции
- здесь наверное надо было бы обсудить, но подумай, попробуй разобраться 
 1. надо написать функцию которая принимает на вход число милисекунд и отдает на выход часы, минуты и милисекунды 
` function getTime (ms) {  
       // ... do stuff
       // ... returns time string
   }`
   2. дальше, в компоненте трека надо эту функцию вызвать там, где ты планируешь выводить время

2023-01-26 05:19 UTC, katekrivets commented
если сильно уменьшить масштаб у строки поиска появляется справа отступ, попробуй поколбасить в браузере и отступов не хватает внутри input , текст прилип к левому краю
<img width="1297" alt="image" src="https://user-images.githubusercontent.com/24584506/214763769-95d0c3c7-e6b0-400b-a614-022c8ec0b6ed.png">

2023-01-26 18:39 UTC, DashaGoryacheva commented on src/components/Album/Album.jsx
> +            <p>ALBUM ID:{albumId}</p>
имеешь ввиду тег р?
это задел на будущее, там же будет что-то помимо одной строки
а сейчас только стрка, поэтому строчный тег:)

2023-01-26 18:51 UTC, DashaGoryacheva commented on src/components/App.jsx
> +            <Route path='/' element={<SearchBlock/>} >
+

2023-01-26 19:57 UTC, DashaGoryacheva commented on src/components/SearchBlock/SearchBlock.jsx
> +          <button className='search-icon'></button>
добавила

2023-01-26 19:58 UTC, DashaGoryacheva commented on src/components/SearchBlock/searchBlock.css
> +    cursor: grab;
исправила
на иконку 'play' тоже добавила

2023-01-26 20:00 UTC, DashaGoryacheva commented on src/components/TrackList.jsx
> +          <ul type='none' className='trackList-item'>
согласна, исправила

2023-01-26 20:50 UTC, DashaGoryacheva commented on webpack.common.js
> + const json = require('./src/components/songs');
нет,убрала

2023-01-26 21:56 UTC, DashaGoryacheva commented on src/components/utils/time.js
> +
установила

2023-01-28 12:39 UTC, DashaGoryacheva commented on src/components/trackList.css
> +    font-family: Arial, "Helvetica Neue";
исправила

2023-01-28 13:30 UTC, DashaGoryacheva commented on src/components/trackList.css
> +    border: 1px groove rgb(114, 113, 113);
добавила

2023-01-28 13:51 UTC, DashaGoryacheva commented on src/components/trackList.css
> +    padding: 2%;
исправила на px, посмотрела в разных масштабах-вроде смотрится хорошо
Не использовала медиа, так как подумала , что в данном случае один раз задать константы паддинга лучше, но если так лучше не делать, то исправлюсь:)

2023-01-28 13:51 UTC, DashaGoryacheva commented on src/components/App.jsx
> +            <Route path='/' element={<SearchBlock/>} >
исправила

2023-01-28 18:56 UTC, DashaGoryacheva commented on src/components/utils/time.js
> +
исправила

2023-01-30 18:47 UTC, katekrivets commented on dist/app.bundle.js.LICENSE.txt
> + * @remix-run/router v1.2.1
а шо это?

2023-01-30 18:47 UTC, katekrivets commented on src/components/TrackList.jsx
> +                  songDuration(songs.tracks.items[item].duration_ms).seconds}
нет ощущения что ты слишком много раз вызываешь одну функцию?

подумай, как вызвать ее один раз, твои идеи?
давай логику с часами равными нулю пока опустим (держи ее в голове) и подумаем как нам решить эту проблему

2023-01-30 18:47 UTC, katekrivets commented on src/components/trackList.css
> +  padding: 3px 15px;
чисто на будущее, padding margin лучше делать кратным 2, так потом проще будет считать)

2023-01-30 18:47 UTC, katekrivets commented on src/components/trackList.css
> +  color: dimgrey;
лучше использовать hex цвета, у тебя просто где-то hex, где-то rgb, где-то просто строки, лучше что-то одно

на заметку тебе, можно сделать палитру и пользоваться ей, тогда точно нигде не ошибешься
https://www.w3schools.com/css/css3_variables.asp

2023-01-30 18:47 UTC, katekrivets commented on src/components/trackList.css
> +  border-radius: 6px;
то же самое с радиусами, создай переменную
https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties

2023-01-30 18:47 UTC, katekrivets commented
![image](https://user-images.githubusercontent.com/24584506/215567523-4559afdf-7bb1-4f35-b6d3-f4ddeadaacbc.png)

2023-01-30 21:41 UTC, DashaGoryacheva commented on src/components/trackList.css
> +  border-radius: 6px;
сделала

2023-01-30 22:08 UTC, DashaGoryacheva commented on src/components/trackList.css
> +  color: dimgrey;
сделала

2023-01-31 19:25 UTC, DashaGoryacheva commented on src/components/trackList.css
> +  padding: 3px 15px;
исправила

2023-02-05 12:31 UTC, DashaGoryacheva commented on src/components/TrackList.jsx
> +                  songDuration(songs.tracks.items[item].duration_ms).seconds}
исправила

2023-02-05 19:56 UTC, katekrivets commented on src/components/utils/populateSongsWithTime.js
> +function populateSongsWithTime(itemsArray, ms) {
почему первый аргумент это itemsArray? разве это не item?

еще ты меня не до конца поняла, смысл был в том, что ты один раз изменяешь весь список, а ты по сути каждый элемент меняешь по отдельности, то есть задачу ты поняла не верно

2023-02-05 19:56 UTC, katekrivets commented on src/components/TrackList.jsx
> +            populateSongsWithTime(item, item.duration_ms),
у меня один вопрос, ты точно поняла что ты здесь сделала и почему это работает? :)

2023-02-05 19:57 UTC, katekrivets commented on src/components/TrackList.jsx
> +            populateSongsWithTime(item, item.duration_ms),
объясни мне почему твой код работает, а вот это нет
[1,2,3].map((item) => (item + 1, item))

2023-02-05 20:08 UTC, katekrivets commented
task2 - Ярлык.lnk - это что за зверь и как он затесался в проект?

2023-02-07 20:31 UTC, merged