React router tracklist
DashaGoryacheva/task-with-webpack pull request #7
Opened 2023-04-11 21:40 UTC by DashaGoryacheva

final version with API muzicbrains.org

2023-04-12 22:25 UTC, katekrivets commented
надо писать названия коммитов в соответствии с тем, что ты в нем исправляла
"first rev" - не информативно, старайся так не делать

2023-04-12 23:03 UTC, katekrivets requested changes

2023-04-12 23:03 UTC, katekrivets commented on package.json
> +    "file-loader": "^6.2.0",
это используется где-то?

2023-04-12 23:03 UTC, katekrivets commented on src/components/Album/Album.tsx
> +  console.log(props.itemsArray);
логи не должны попадать в продакшен

2023-04-12 23:03 UTC, katekrivets commented on src/components/Album/Album.tsx
> +    return album;
я не понимаю что делает эта функция, как по мне так ничего
если она ничего не делает - удалить

2023-04-12 23:03 UTC, katekrivets commented on src/components/Album/Album.tsx
> +  console.log(exactAlbumItem);
аналогично - убрать

2023-04-12 23:03 UTC, katekrivets commented on src/components/Album/Album.tsx
> +        return fetch(`https://coverartarchive.org/release/${res.id}/front`)
вынести в api

2023-04-12 23:03 UTC, katekrivets commented on src/components/Album/Album.tsx
> +    //в типизации нет имени артиста, пришлось залезть в itemsArray
это к чему сообщение?

2023-04-12 23:03 UTC, katekrivets commented on src/components/Album/Album.tsx
> +                    )}{" "} */}
какие-то тут у нас кусочки)

2023-04-12 23:03 UTC, katekrivets commented on src/components/Artist/Artist.tsx
> +      console.log(result);
удолить

2023-04-12 23:03 UTC, katekrivets commented on src/components/SearchBlock/SearchBlock.tsx
> +            searchTrack(props.value)
два раза одна и та же функция, почему бы не вынести ее на уровень компонента и не написать один раз и избавиться от повторяющегося кода?

2023-04-12 23:03 UTC, katekrivets commented on src/components/SearchBlock/searchBlock.css
> +  background-image: url(data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iaXNvLTg4NTktMSI/Pg0KPCEtLSBHZW5lcmF0b3I6IEFkb2JlIElsbHVzdHJhdG9yIDE2LjAuMCwgU1ZHIEV4cG9ydCBQbHVnLUluIC4gU1ZHI
ничесе ты придумала :) 
почему не ./musicplaceholder.jpg? 
или что тут

2023-04-12 23:03 UTC, katekrivets commented on src/components/Track/Track.tsx
> +      .then((r) => console.log(r));
есть три типа логов 
console.log
console.warn
console.error 
может еще какие-то есть, старайся использовать соответствующие

2023-04-12 23:03 UTC, katekrivets commented on src/components/Track/Track.tsx
> +      `https://coverartarchive.org/release/${trackItemArray[0].releases[0].id}/front`
аналогично, вынести в api

2023-04-12 23:03 UTC, katekrivets commented on src/components/TrackListItem/TrackListItem.tsx
> +      `https://coverartarchive.org/release/${props.track.releases[0].id}/front`
тоже в api, это все одна и та же функция судя по всему

2023-04-12 23:03 UTC, katekrivets commented on src/components/TrackListItem/TrackListItem.tsx
> +  const [url, setUrl] = useState<any>(null);
почему не string?

2023-04-12 23:03 UTC, katekrivets commented on src/components/Album/Album.tsx
> +  const [isLoading, setIsLoading] = useState<any>(true);
а тут почему any, это ж boolean

2023-04-12 23:03 UTC, katekrivets commented on src/components/Album/Album.tsx
> +  const [albumObject, setAlbumObject] = useState<any>();
а какого типа у нас albumObject ?

2023-04-12 23:03 UTC, katekrivets commented on src/components/Artist/Artist.tsx
> +  if (isLoading === true) {
это правильно, но на самом деле у тебя isLoading и так сам по себе boolean
то есть ты можешь писать 
if(isLoading) и это будет работать

2023-04-12 23:03 UTC, katekrivets commented on src/components/Artist/artist.css
> +  background-image: url("meladze.jpg");
а это что за зверь? :)

2023-04-12 23:03 UTC, katekrivets commented on src/loader/loader.js
> +const Loader = () => {
не хочу быть занудой, но мне кажется это все-таки должен быть jsx файл

2023-04-12 23:03 UTC, katekrivets commented on src/loader/loader.js
> +const Loader = () => {
ну или tsx

2023-04-16 19:32 UTC, DashaGoryacheva commented on package.json
> +    "file-loader": "^6.2.0",
убрала

2023-04-16 21:10 UTC, DashaGoryacheva commented on src/components/Album/Album.tsx
> +  const [isLoading, setIsLoading] = useState<any>(true);
+

2023-04-16 21:11 UTC, DashaGoryacheva commented on src/loader/loader.js
> +const Loader = () => {
+

2023-04-16 21:15 UTC, DashaGoryacheva commented on src/components/Artist/artist.css
> +  background-image: url("meladze.jpg");
а это я так навала фоновую заливку для компонента с артистами)
исправила название

2023-04-16 21:17 UTC, DashaGoryacheva commented on src/components/Album/Album.tsx
> +    return album;
она фильтрует из массива с релизами  только альбом с нужным мне айдишником. Затем я использую этот элемент массива после фильтра для вывода имени  артиста на экран

2023-04-17 00:58 UTC, katekrivets commented on src/components/Artist/artist.css
> +  background-image: url("meladze.jpg");
я не нашла в проекте его почему-то

2023-04-17 00:58 UTC, katekrivets commented on src/components/Album/Album.tsx
> +    return album;
ну если ты на код посмотришь она ничего не фильтрует

2023-04-18 18:10 UTC, DashaGoryacheva commented on src/components/Album/Album.tsx
> +    return album;
поняла,исправила

2023-04-18 18:12 UTC, DashaGoryacheva commented on src/components/Artist/artist.css
> +  background-image: url("meladze.jpg");
уже иначе будет выглядеть компонент артиста, поэтому этот jpg убрала
а так он был в css компонента artist

2023-04-18 18:58 UTC, DashaGoryacheva commented on src/components/Album/Album.tsx
> +        return fetch(`https://coverartarchive.org/release/${res.id}/front`)
+

2023-04-18 22:40 UTC, DashaGoryacheva commented on src/components/Album/Album.tsx
> +  const [albumObject, setAlbumObject] = useState<any>();
исправила

2023-04-21 15:28 UTC, DashaGoryacheva commented on src/components/Album/Album.tsx
> +  console.log(props.itemsArray);
+

2023-04-21 15:28 UTC, DashaGoryacheva commented on src/components/Album/Album.tsx
> +  console.log(exactAlbumItem);
+

2023-04-22 00:02 UTC, katekrivets approved these changes

2023-04-22 00:02 UTC, katekrivets commented on .babelrc
> +      "plugins": ["transform-remove-console"]
судя по всему не помогло, проверь почему

2023-04-22 00:02 UTC, katekrivets commented on src/api/index.tsx
> +  return fetch(`https://coverartarchive.org/release/${id}/front`).then(
а зачем тут then?

2023-04-22 00:02 UTC, katekrivets commented on src/components/App.tsx
> +    console.log(this.state);
можно наверное грохнуть

2023-04-22 00:02 UTC, katekrivets commented on src/components/SearchBlock/searchBlock.css
> +  background-image: url(data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iaXNvLTg4NTktMSI/Pg0KPCEtLSBHZW5lcmF0b3I6IEFkb2JlIElsbHVzdHJhdG9yIDE2LjAuMCwgU1ZHIEV4cG9ydCBQbHVnLUluIC4gU1ZHI
все еще жду ответ шо это

2023-04-22 00:02 UTC, katekrivets commented on src/components/Track/Track.tsx
> +      .then((r) => console.log(r));
обрати на это внимание

2023-04-22 00:03 UTC, katekrivets commented
посмотри еще комментарии которые я оставила, но я считаю это уже достойная версия поэтому предлагаю вмержить и следующую делать в новой ветке

2023-04-22 00:03 UTC, merged